reload on serviceaccount change

diff --git a/templates/configmap.yaml b/templates/configmap.yaml
--- a/templates/configmap.yaml
+++ b/templates/configmap.yaml
@@ -4,13 +4,38 @@ kind: ConfigMap
 metadata:
   name: metricsmultiplexer
 data:
+  reloader.sh: |
+    #!/bin/sh
+    set -eu -o pipefail
+
+    # reload nginx config with new service account token
+    TOKEN=`cat /var/run/secrets/kubernetes.io/serviceaccount/token`
+    cat multiplexer-nginx.conf | sed "s/KUBERNETESAUTHTOKEN/$TOKEN/" > /etc/nginx/conf.d/default.conf
+
+    nginx -t -q
+    if [ $? -eq 0 ]
+    then
+      # config is valid, reload nginx config
+      set +e # don't exit on error (e.g. nginx not yet started)
+      nginx -q -s reload
+      set -e
+    else
+      # config is invalid, log the error and exit
+      nginx -t
+      exit 1
+    fi
   entrypoint.sh: |
     #!/bin/sh
+    set -eu -o pipefail
 
     # Generate self-signed SSL certs (not great!)
-    apk add openssl && openssl req -x509 -nodes -days 365 -subj "/C=NA/ST=NA/O=NA/CN=NA" -newkey rsa:2048 -keyout /etc/nginx/ssl.key -out /etc/nginx/ssl.crt
+    apk add openssl inotify-tools && openssl req -x509 -nodes -days 3650 -subj "/C=NA/ST=NA/O=NA/CN=NA" -newkey rsa:2048 -keyout /etc/nginx/ssl.key -out /etc/nginx/ssl.crt
 
-    cat multiplexer-nginx.conf > /etc/nginx/conf.d/default.conf
+    reloader.sh # initial config
+
+    # Watch for changes to the bound service account token or configmap and reload nginx config
+    inotifyd reloader.sh /var/run/secrets/kubernetes.io/serviceaccount/token:n &
+    inotifyd reloader.sh /multiplexer-nginx.conf:n &
 
     # Finally, start up nginx
     nginx -g 'daemon off;'
